default_stages: [commit]
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
      - id: black
        language_version: python3
        args: [--quiet]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: [--max-line-length=1024, --extend-ignore=E203]
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.2.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v6.0.1
    hooks:
      - id: clang-format
  - repo: https://github.com/hadolint/hadolint
    rev: v2.5.0
    hooks:
      - id: hadolint-docker
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.28.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
